        ' Throws a new exception.
        Throw New System.Exception("An exception has occurred.")